name: HCFPlus
main: life.steeze.hcfplus.HCFPlugin
description: Simply HCF
commands:
  faction:
    description: Use factions
    aliases: [f, factions, fac]
  savefactions:
    description: Save factions.yml
permissions:
  hcf.admin:
    default: op
api-version: 1.14
version: 1.20
author: ViperCobra
softdepend: [PlaceholderAPI]